### ISSUE TITLE
Ayuda setupeando todo lo necesario para correr

### ISSUE THREAD

**Issue by JeysonFlores** [Miqueas/TapeDeck#7]
Hola @Miqueas , eres el primer desarrollador de Gtk + Lua que me he encontrado xd. Hace tiempo me interesó usar también Gtk y Lua juntos pero decidí usar Python para mi proyecto [Hasher](https://github.com/JeysonFlores/hasher) . No soy ningún experto en Lua por lo que no sé muy bien como setupear todo, instalé lua 5.2 y luarocks, además de instalar lgi. Pero cuando mando a llamar lgi me dice:
`lua: test.lua:9: module 'lgi' not found:
	no field package.preload['lgi']
	no file '/usr/local/share/lua/5.2/lgi.lua'
	no file '/usr/local/share/lua/5.2/lgi/init.lua'
	no file '/usr/local/lib/lua/5.2/lgi.lua'
	no file '/usr/local/lib/lua/5.2/lgi/init.lua'
	no file '/usr/share/lua/5.2/lgi.lua'
	no file '/usr/share/lua/5.2/lgi/init.lua'
	no file './lgi.lua'
	no file '/usr/local/lib/lua/5.2/lgi.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/lgi.so'
	no file '/usr/lib/lua/5.2/lgi.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './lgi.so'
stack traceback:
	[C]: in function 'require'
	test.lua:9: in main chunk
	[C]: in ?
`
No hay muchos desarrolladores de Lua y Gtk para preguntar por ayuda. Pero creo que es por la versión de luarocks. Gracias de antemano.

**Comment by darltrash** [comment]
Creo que no has instalado LGI de forma correcta, estas en linux?
Si es asi, podrias correr:
`luarocks --help`
Y mostrarnos el output?

**Comment by diazvictor** [comment]
@JeysonFlores Ergaaa xd

**Comment by JeysonFlores** [comment]
Estoy actualmente en Elementary OS 6 Odin (Basado en Ubuntu 20.04)
`luarocks --help` me da:
```
LuaRocks 2.4.2, a module deployment system for Lua

NAME
	/usr/bin/luarocks - LuaRocks main command-line interface

SYNOPSIS
	/usr/bin/luarocks [--from=<server> | --only-from=<server>] [--to=<tree>] [VAR=VALUE]... <command> [<argument>] 

```
Luego los comandos y ya al final:

```
CONFIGURATION
	Lua version: 5.2
	Configuration files:
		System: /etc/luarocks/config.lua (ok)
		User  : /home/jeyson/.luarocks/config-5.2.lua (not found)

	Rocks trees in use: 
		/home/jeyson/.luarocks
		/usr/local

```

**Comment by sodomon2** [comment]
@JeysonFlores El problema puede ser porque tal vez instalaste lgi para lua5.1 pero no para lua5.2.

ya que viendo el error 
`/usr/local/lib/lua/5.2/lgi.so` y `/usr/lib/lua/5.2/lgi.so` no existen por lo que creo que no lo tienes instalado para lua5.2

**Comment by JeysonFlores** [comment]
Hace un rato instalé lua 5.1 y me da el mismo resultado:

```
lua: test.lua:9: module 'lgi' not found:
	no field package.preload['lgi']
	no file './lgi.lua'
	no file '/usr/local/share/lua/5.1/lgi.lua'
	no file '/usr/local/share/lua/5.1/lgi/init.lua'
	no file '/usr/local/lib/lua/5.1/lgi.lua'
	no file '/usr/local/lib/lua/5.1/lgi/init.lua'
	no file '/usr/share/lua/5.1/lgi.lua'
	no file '/usr/share/lua/5.1/lgi/init.lua'
	no file './lgi.so'
	no file '/usr/local/lib/lua/5.1/lgi.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lgi.so'
	no file '/usr/lib/lua/5.1/lgi.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	test.lua:9: in main chunk
	[C]: ?

```

**Comment by sodomon2** [comment]
> Hace un rato instalé lua 5.1 y me da el mismo resultado:
> 
> ```
> lua: test.lua:9: module 'lgi' not found:
> 	no field package.preload['lgi']
> 	no file './lgi.lua'
> 	no file '/usr/local/share/lua/5.1/lgi.lua'
> 	no file '/usr/local/share/lua/5.1/lgi/init.lua'
> 	no file '/usr/local/lib/lua/5.1/lgi.lua'
> 	no file '/usr/local/lib/lua/5.1/lgi/init.lua'
> 	no file '/usr/share/lua/5.1/lgi.lua'
> 	no file '/usr/share/lua/5.1/lgi/init.lua'
> 	no file './lgi.so'
> 	no file '/usr/local/lib/lua/5.1/lgi.so'
> 	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lgi.so'
> 	no file '/usr/lib/lua/5.1/lgi.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'
> stack traceback:
> 	[C]: in function 'require'
> 	test.lua:9: in main chunk
> 	[C]: ?
> ```

Mmm el error podria ser que no instalaste lgi de forma correcta como dijo @darltrash.
Puedes decirme como instalaste lgi??

**Comment by JeysonFlores** [comment]
Tal cual dice su [repositorio](https://github.com/pavouk/lgi):
`luarocks install lgi
`
Bueno, solo que no me dejaba así nomás tuve que agregar un `--local`

**Comment by sodomon2** [comment]
> Tal cual dice su [repositorio](https://github.com/pavouk/lgi):
> `luarocks install lgi `

Ok,entonces hazle un ls -l `/usr/local/lib/lua/5.2/` y subes la salida

Esto te puede interesar https://github.com/pavouk/lgi/issues/196

**Comment by Miqueas** [comment]
> Tal cual dice su [repositorio](https://github.com/pavouk/lgi):
> `luarocks install lgi `
> Bueno, solo que no me dejaba así nomás tuve que agregar un `--local`

Ahí tienes el error, lgi se instaló pero en tu carpeta de usuario ya que le pasaste el flag `--local` a luarocks. En su lugar intenta con: `sudo luarocks install lgi`

**Comment by JeysonFlores** [comment]
@Miqueas esto último si funciono. xDDD chale solo era poner sudo :( Pero nice, ya podré hacer pruebas

**Comment by Miqueas** [comment]
> @Miqueas esto último si funciono. xDDD chale solo era poner sudo :( Pero nice, ya podré hacer pruebas

;)

**Comment by JeysonFlores** [comment]
Gracias a todos kbrones

**Comment by Miqueas** [comment]
> Gracias a todos kbrones

No hay problema

**Comment by darltrash** [comment]
@JeysonFlores ;)

**Comment by sodomon2** [comment]
@JeysonFlores :)👌😎
