### ISSUE TITLE
Build System?

### ISSUE THREAD

**Issue by JeysonFlores** [Miqueas/TapeDeck#8]
Qué onda cabros, desde que pude correr LGI con Lua me puse a hacer pruebas, y para practicar inicié un repositorio que sería algo así como la plantilla de una aplicación que use Lua, Gtk, Granite, Handy y Flatpak según los estándares de Elementary OS. La plantilla es [Elementary-Lua](https://github.com/JeysonFlores/ElementaryLua), el codigo persé ya lo acabé, ahora estoy viendo como puñetas instalar la aplicación pero Lua maneja las rutas y los archivos de una manera super curseada, tal parece que solo busca en directorios específicos y en el directorio de dónde se ejecuta la app, por lo que si yo en lugar de ejecutar el archivo principal en la carpeta raiz del proyecto lo ejecuto desde otro directorio los archivos los va a buscar desde ese directorio (super raro todo). Hice este Makefile que copia todos los archivos a /usr/bin para su ejecución pero oh sorpresa, cuando es ejecutado el archivo main no encuentra los demás archivos.

```Makefile
.PHONY: all install uninstall
PREFIX ?= /usr

install:
	install -D -m 0755 com.github.jeysonflores.elementarylua $(PREFIX)/bin/com.github.jeysonflores.elementarylua
	install -D -m 0644 src/Application.lua $(PREFIX)/bin/elementarylua/Application.lua
	install -D -m 0644 src/MainWindow.lua $(PREFIX)/bin/elementarylua/MainWindow.lua
	install -D -m 0644 src/WelcomeView.lua $(PREFIX)/bin/elementarylua/WelcomeView.lua
```
Casi todo los tutoriales que encuentro en internet de como buildear una app en Lua ponen ejemplos de UNO SOLO ARCHIVO cuando lo realista es que una app tenga varios archivos. Me puse a ver este repositorio a ver como configuraba el build system pero parece que no tiene xD. Alguien sabe como solucionar esto?

**Comment by Miqueas** [comment]
@JeysonFlores Bueno si, es cierto que el manejo de rutas con Lua (específicamente en lo que respecta a cargar cosas con `require()`) es un tanto raro, sin embargo eso lo puedes solucionar modificando las rutas de carga, déjame buscar en la documentación cómo era que se hacía y te comento acá

**Comment by JeysonFlores** [comment]
Creo que ya lo solucioné, tuve que agregar la ruta estática de dónde se van a instalar los archivos

```Lua
package.path = package.path .. ";/usr/bin/elementarylua/?.lua"
require "WelcomeView"
```

**Comment by Miqueas** [comment]
> Creo que ya lo solucioné, tuve que agregar la ruta estática de dónde se van a instalar los archivos
> 
> ```lua
> package.path = package.path .. ";/usr/bin/elementarylua/?.lua"
> require "WelcomeView"
> ```

Oh! Bien, precisamente eso te iba a decir, pero no recordaba como funcionaba xd otras opciones son `dofile()` and `loadfile()`, pero hmm... No sé si darán el mismo resultado :thinking:

**Comment by Miqueas** [comment]
Por cierto lo que estás haciendo se ve realmente interesante, espero que puedas culminarlo sin problemas! :)

**Comment by JeysonFlores** [comment]
Primero intenté con `loadfile` y con `dofile` pero no me convenció su uso, `require` está bien sólo por ese pequeño detalle que busca en sólo lugares especificos, justo cuando iba a ver como usar loadfile encontré una pregunta en StackOverflow que te decía como interactuar con package.path

**Comment by Miqueas** [comment]
@JeysonFlores Pues supongo que depende de lo que quieres hacer y cómo lo vas a hacer, si require() te resulta mejor pues está bien :P

**Comment by JeysonFlores** [comment]
Gracias xd, quiero hacer esta template para ver si más gente de la comunidad de Lua o de la comunidad de Elementary OS se anime a hacer un proyecto. En elementary OS se usa mucho Vala y por eso la gente cree que es el único lenguaje que se puede utilizar para GTK y les da pereza aprenderlo (los entiendo a mi también me da) pero como tal vez creen que no pueden usar Lua para desarrollar no se animan

**Comment by Miqueas** [comment]
@JeysonFlores Bueno realmente se supone que Vala es el lenguaje el cual los devs de elementary alientan a que usen para las apps que desarrollan, más sin embargo es cierto que no necesariamente sea el único hasta donde sé 🤔

**Comment by darltrash** [comment]
@Miqueas Sinceramente creo que portear el proyecto a vala o a rust seria una mucha mejor idea que usar lua+lgi ya que, tristemente, lgi es muy lacklustre, especialmente con standares actuales como libhandy/libadwaita/gtk4, pero tambien eso seria altamente completo porque requeriria de conocimiento semi-avanzado de vala y rust lo cual tomaria MUCHO tiempo

**Comment by Miqueas** [comment]
@darltrash Si, ese es el pequeño gran detalle con LGI, tiene sus... Problemas

**Comment by darltrash** [comment]
@Miqueas jaja sus

**Comment by Miqueas** [comment]
@Miqueas Sin embargo no significa que no sea usable, simplemente hay que tener paciencia supongo xd

**Comment by darltrash** [comment]
@Miqueas lo dudo, gtk3 ya esta en segundo plano y sinceramente dudo que haya una verdadera razon de seguir usando gtk3

**Comment by JeysonFlores** [comment]
Se supone que la idea es que si tú eres un programador de Lua y quieres aportar a la comunidad desarrollando tus aplicaciones no necesitas aprender nada más, si ya sabes Lua puedes hacerlo, es sólo que no hay mucha info.

**Comment by JeysonFlores** [comment]
@darltrash en la comunidad de eOS todavía se usa Gtk3, probablemente para la próxima versión de eOS pasen a Gtk 4 pero como las apps de eOS se empaquetan en flatpak, todavía se podrían usar las apps desarrolladas en Gtk 3

**Comment by Miqueas** [comment]
> Se supone que la idea es que si tú eres un programador de Lua y quieres aportar a la comunidad desarrollando tus aplicaciones no necesitas aprender nada más, si ya sabes Lua puedes hacerlo, es sólo que no hay mucha info.

Por supuesto

**Comment by darltrash** [comment]
@JeysonFlores el problema es que a este paso, quiza nunca lgi tenga soporte a gtk4 y seria mejor simplemente saltar del vagon y irnos lejos a el mundo de los lenguajes compilados.

**Comment by Miqueas** [comment]
> @darltrash en la comunidad de eOS todavía se usa Gtk3, probablemente para la próxima versión de eOS pasen a Gtk 4 pero como las apps de eOS se empaquetan en flatpak, todavía se podrían usar las apps desarrolladas en Gtk 3

Tocará ver cómo se le hace al Lua en Flatpak porque no imagino cómo xd

**Comment by Miqueas** [comment]
> @JeysonFlores el problema es que a este paso, quiza nunca lgi tenga soporte a gtk4 y seria mejor simplemente saltar del vagon y irnos lejos a el mundo de los lenguajes compilados.

Pues entre pasar elementary a GTK 4 y que LGI tenga soporte para este, no sé cual de los dos será primero, principalmente porque no se sabe nada del dev de LGI (o al menos yo ni idea)

**Comment by darltrash** [comment]
@Miqueas eso es un punto muy muy muy valido, pero no creo que sea bueno depender de una apuesta, aun asi,creo que eso justifica el uso de lgi

**Comment by Miqueas** [comment]
@darltrash de cualquier forma, mientras GTK 3 aún no esté deprecado oficialmente, LGI aún es una opción

**Comment by JeysonFlores** [comment]
> Tocará ver cómo se le hace al Lua en Flatpak porque no imagino cómo xd

Ya lo hice, lo más difícil fué añadir al `package.path` y al `package.cpath` los directorios de flatpak.

**Comment by Miqueas** [comment]
@JeysonFlores nice
